# kubernetes/couchdb-deployment-env.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  namespace: obsidian-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb:3.5.0
          env:
            # 基本設定
            - name: COUCHDB_USER
              value: "admin"
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-secrets
                  key: admin-password
            - name: COUCHDB_SECRET
              valueFrom:
                secretKeyRef:
                  name: couchdb-secrets
                  key: cookie

            # セキュリティ設定
            - name: COUCHDB_REQUIRE_VALID_USER
              value: "true"

            # CORS設定
            - name: COUCHDB_ENABLE_CORS
              value: "true"
            - name: COUCHDB_CORS_CREDENTIALS
              value: "true"
            - name: COUCHDB_CORS_ORIGINS
              value: "*"
            - name: COUCHDB_CORS_HEADERS
              value: "accept,authorization,content-type,origin,referer,x-requested-with"
            - name: COUCHDB_CORS_METHODS
              value: "GET,PUT,POST,HEAD,DELETE"

          ports:
            - containerPort: 5984
              name: couchdb

          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /_up
              port: 5984
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

      volumes:
        - name: couchdb-data
          persistentVolumeClaim:
            claimName: couchdb-data-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data-pvc
  namespace: obsidian-sync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
